### ISSUE TITLE
test

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/node-subprocess#6]
testing hello@user.com

**Comment by tomholub** [comment]
here

![image](https://user-images.githubusercontent.com/6306961/118228351-8f1cbd80-b479-11eb-8c59-49ddc369038f.png)

**Comment by seisvelas** [comment]
Sorry, typo. This fixes it: https://github.com/FlowCrypt/node-subprocess/pull/7

**Comment by tomholub** [comment]
test hello@there.com

**Comment by seisvelas** [comment]
Let's try it again: test hello@there.com

**Comment by tomholub** [comment]
retest@hello.here
